version: '2'

services:

  mysql:
    image: mysql
    command: --character-set-server=utf8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: password_of_redmine
    networks:
      default:
        aliases:
          - mysql
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mysql:/var/lib/mysql:rw

  redmine:
    build: ./
    ports:
      - 3000:3000
    environment:
      REDMINE_DB_MYSQL: mysql
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: password_of_redmine
      # plugins
      REDMINE_PLUGIN_redmine_changeauthor:          https://github.com/ngyuki/redmine_changeauthor.git
      REDMINE_PLUGIN_redmine_fetch_changesets_post: https://github.com/ngyuki/redmine_fetch_changesets_post.git
      REDMINE_PLUGIN_redmine_redcarpet_viewer:      https://github.com/ngyuki/redmine_redcarpet_viewer.git
      REDMINE_PLUGIN_redmine_rouge:                 https://github.com/ngyuki/redmine_rouge.git
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - files:/usr/src/redmine/files:rw
    depends_on:
      - mysql

volumes:
  files:
  mysql:
